FROM node:18-alpine AS builder
WORKDIR /app

# Продакшн API URL
ENV REACT_APP_API_URL=http://45.131.41.192:5050/api/v1

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
